### ISSUE TITLE
The "\SoftLayer\ObjectMask" class doesn't exist to create an object mask

### ISSUE THREAD

**Issue by rubercuellar** [softlayer/softlayer-api-php-client#18]
According to git example:

``` php
$objectMask = new \SoftLayer\ObjectMask();
$objectMask->updates;
$objectMask->assignedUser;
$objectMask->attachedHardware->datacenter;
$client->setObjectMask($objectMask);
```

The following exception is displayed:

```
Fatal error: Class 'SoftLayer\ObjectMask' not found in ...
```

It works fine doing the following change:

``` php
$objectMask = new \SoftLayer\Common\ObjectMask();
```

**Comment by phansys** [comment]
[My bad](https://github.com/softlayer/softlayer-api-php-client/pull/10/files#diff-8aa641a619b8ebeca0116d41774daf45R70) @rubercuellar.
Could you create a PR in order to fix `README.md`?
